### ISSUE TITLE
[Bug]Parse configuration file path failure: java.lang.NoSuchMethodError: org.apache.commons.cli.Options.hasShortOption(Ljava/lang/String;)Z

### ISSUE THREAD

**Issue by dadalongvs** [apache/inlong#4835] opened 2022-07-01 09:08 UTC
### What happened

![image](https://user-images.githubusercontent.com/108457248/176863295-1f4253fd-620f-4b24-a112-ebea949a8f3c.png)

### What you expected to happen

。

### How to reproduce

![Uploading image.png…]()

### Environment

20.04.1-Ubuntu

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment] 2022-07-01 09:35
@dadalongvs, thanks, I got it, let me see

**Comment by gosonzhang** [comment] 2022-07-01 11:35
@dadalongvs, did you run the binary package directly and report the error, or did you run the error after compiling the source code?

From this point of view[1], it should be caused by the wrong version of the relevant dependency package:
1. https://stackoverflow.com/questions/51539130/apache-commons-cli-defaultparser-nosuchmethod-error

**Comment by dadalongvs** [comment] 2022-07-01 11:40
The error reported by executing “tubemq.sh master start“”, I don't know whether the commons-cli under lib conflicts with other packages in this directory or the jar packages in other directories. I have not replaced the jar packages in this directory.

**Comment by gosonzhang** [comment] 2022-07-04 12:08
@dadalongvs, can you compile the source code in the inlong-tubemq directory? Confirm that there is no problem with the result compiled from the source code

I have no problem with running the local source code after compiling, but there is a problem with running it directly through the released binary package. I am looking at where the problem is caused.

Thanks!

**Comment by dadalongvs** [comment] 2022-07-04 12:29
The master and broker that start the compiled tubemq-server will also have this error

**Comment by gosonzhang** [comment] 2022-07-04 14:44
I compiled it from the source and have run it many times and it's ok:
![image](https://user-images.githubusercontent.com/14038849/177176816-b9c6d56b-2a13-47de-b6e3-9216b72f0ecb.png)
![image](https://user-images.githubusercontent.com/14038849/177176866-4e6ae0e5-fc02-49f2-8dc2-40a687c48d50.png)
![image](https://user-images.githubusercontent.com/14038849/177177158-03ded6a1-65b1-48f4-80f8-ce7d46e78ef8.png)
![image](https://user-images.githubusercontent.com/14038849/177177332-5b37ea86-d31b-4a79-a765-f1815f13dc71.png)

**Comment by dockerzhang** [comment] 2022-07-13 01:56
@dadalongvs please download the latest binary package and try again, thanks.
https://github.com/apache/inlong/discussions/3368

**Comment by dockerzhang** [comment] 2022-07-25 08:53
it's not appeared again, so close it first.

**Closed by dockerzhang** 2022-07-25 08:53 UTC
Labels: type/bug

**Comment by dadalongvs** [comment] 2022-10-11 08:23
OK, I will try it a few more times



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/04/2022 22:45 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [apache/inlong] [Bug]Parse configuration file path failure: java.lang.NoSuchMethodError: org.apache.commons.cli.Options.hasShortOption(Ljava/lang/String;)Z (Issue #4835) |

I compiled it from the source and have run it many times and it's ok:
