### ISSUE TITLE
[Bug]使用helm部署inlong服务到内网环境的kubernetes集群

### ISSUE THREAD

**Issue by HYBG-1126** [apache/inlong#7362] opened 2023-02-13 08:01 UTC
### What happened

安装环境不能链接网络，经过调整，大部分的服务在k8s集群成功运行，但是dashboard始终不成功，出现以下报错；

 2023/02/09 11:01:55 [emerg] 7#7: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

做过的努力：
1、修改nginx的default.conf配置，注释ipv6的80端口监听；
2、增加以下配置到/etc/sysctl.conf中
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.eth1.disable_ipv6 = 1
net.ipv6.conf.eth2.disable_ipv6 = 1
net.ipv6.conf.eth3.disable_ipv6 = 1

### What you expected to happen

猜测问题原因是k8s集群没有开启ipv6导致

### How to reproduce

我不认为这个问题可以简单重现

### Environment

inlong version：1.5.0

kubectl version:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10"}

k8s环境，不能链接网络，没有开启ipv6

### InLong version

1.5.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment] 2023-02-13 08:04
@HYBG-1126 please add the version for the k8s cluster.

**Comment by HYBG-1126** [comment] 2023-02-14 08:04
> @HYBG-1126 please add the version for the k8s cluster.

已添加

**Comment by dockerzhang** [comment] 2023-02-27 03:07
I tried the latest helm chart, but it could not reproduce this error, so close it.

**Closed** 2023-02-27 03:07 UTC
Labels: type/bug
